### ISSUE TITLE
Batch Process

### ISSUE THREAD

**Issue by damontgomery** [d8-contrib-modules/field_encrypt#11]
Right now the encrypt_stored_field() and decrypt_stored_field() methods do not use a batch process.

This may become an issue if there is a large number of entities on a site and it may be worth adding a batch process to the module.

**Comment by svendecabooter** [comment]
Todo: check if locking current entities is possible while doing the updates, to avoid data corruption.
See: https://github.com/d8-contrib-modules/field_encrypt/pull/26#issuecomment-195758476

**Comment by svendecabooter** [comment]
Todo: add extra error handling:
https://github.com/d8-contrib-modules/field_encrypt/pull/26#discussion_r55922652

**Comment by svendecabooter** [comment]
PR merged
