### ISSUE TITLE
Research options on the "encrypt" field when creating a new entity field

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/field_encrypt#2]
1. How do we extend the field creation process to create a new field for encrypt option?
2. Should we separate this by field type? (e.g. different classes for types of fields, turn different field types on and off based on settings?)

**Comment by damontgomery** [comment]
@nerdstein, I used the ThirdPartySettings pattern to extend the Config Entity (Field Storage). This adds a "encrypt" "field" to all fields. I've already merged the code and am going to work on some of the other portions of the module. Please close if this pattern seems to fit the needs of the module.

**Comment by damontgomery** [comment]
closing and have remaining items in new issues.
