### ISSUE TITLE
add UninstallValidator

### ISSUE THREAD

**Issue by svendecabooter** [d8-contrib-modules/field_encrypt#21]
Add an UninstallValidator service, that checks if field_encrypt still has fields encrypted, before being able to be uninstalled.

**Comment by svendecabooter** [comment]
To check if this is still necessary.
Drupal core will by default throw an exception if entities still exist of the entity type defined by the module to be uninstalled.

So currently this will already result in the following error (via Drush):

exception 'Drupal\Core\Extension\ModuleUninstallValidatorException' with message 'The following reasons prevent the modules from being   [error]
uninstalled: There is content for the entity type: Encrypted field value'.

**Comment by nerdstein** [comment]
Do we need to ask the user to do something before uninstalling? My guess is we might want to decrypt everything

**Comment by svendecabooter** [comment]
As long as there is still encrypted data in the site (EncryptedFieldValue entities), the validation will fail and the field_encrypt module will not be able to uninstall.
So the user will need to take action and make sure every field is decrypted, before uninstall will be able to happen.

I don't think it will be possible to do it automatically, and probably not advised either. We would need to interact between the moment the user clicks "Uninstall", and the moment the validator throws an error that there is still encrypted content. Decrypting everything on the fly at that point might result in timeouts, if not handled by a queue. Also the user might want to get the error instead, reminding him that uninstalling the module will change his data (e.g. someone who mistakes the D8 uninstall functionality for the D7 enable-disable module functionality - not wanting to remove stuff, but just deactivate temporarily)

Or do you suggest we add some UI to have a one-click-decrypt-everything feature?

**Comment by nerdstein** [comment]
I do recommend we do that. Or, have an administrative page that lists out every place in which fields are encrypted with a button to remove encryption for a line item (with a warning, of course). Or, both removal of all encryption and line items :) I want to enable users to quickly uninstall, if they so desire.

**Comment by svendecabooter** [comment]
Described functionality has been added
