### ISSUE TITLE
Fatal errors in \Drupal\field_encrypt\FieldEncryptProcessEntities::checkField()

### ISSUE THREAD

**Issue by TravisCarden** [d8-contrib-modules/field_encrypt#31]
`\Drupal\field_encrypt\FieldEncryptProcessEntities::checkField()` tries to call two non-existent methods, `\Drupal\Core\Field\BaseFieldDefinition::get()` and `Drupal\Core\Field\BaseFieldDefinition::getThirdPartySetting()`, resulting in fatal errors. I experience them when attempting to log into my site after having just installed the module.

**Comment by svendecabooter** [comment]
Fixed in master
