### ISSUE TITLE
Field Encrypt incompatible with Workbench Moderation

### ISSUE THREAD

**Issue by TravisCarden** [d8-contrib-modules/field_encrypt#37]
I'm trying to implement this module on my project. I've succeeded in getting selected fields on a given content type encrypted, but I haven't found any scenario in which they ever get decrypted again--neither on node display nor on node edit accessed as user 1, whom I created my test nodes with. I can see the rows in `encrypted_field_data`, and I see `field_encrypt_entity_storage_load()`, which purports to do the decryption. What am I missing? Is there some kind of code or configuration needed to define the business rules for when decryption actually takes place?

**Comment by svendecabooter** [comment]
That would probably be caused by some bug...
Have you tried clearing your cache?

Upon displaying the node, are you seeing "[ENCRYPTED]" instead of what should be the decrypted value? Or just nothing at all?

**Comment by TravisCarden** [comment]
Yes, I have cleared cache.

I am seeing "[ENCRYPTED]" instead of the decrypted values.

**Comment by svendecabooter** [comment]
Have you changed the field encryption settings after these nodes were created?

**Comment by TravisCarden** [comment]
No. I configured the field storage first, then created my test nodes.

**Comment by svendecabooter** [comment]
Hmm do you have steps to reproduce this on a clean Drupal installation?
Are you using 8.0.x or 8.1.x?
And using the latest code in master branch?

**Comment by TravisCarden** [comment]
I'm using core 8.1.x and the latest code in the master branch of `field_encrypt`. I tried to reproduce the problem on a fresh Drupal installation and was unable to do so. Presumably, then, it's a configuration issue or module interaction in my setup. Are there any known issues with revisioning or `workbench_moderation`, by chance? Or conversely, has anyone successfully used the two modules together--`field_encrypt` and `workbench_moderation`?

**Comment by svendecabooter** [comment]
I'll have to check out the interaction with these 2 modules.
The field encryption interacts on revisions as well, since fields can have multiple( encrypted) revisions, so maybe there's some clashing functionality there... Will investigate.

**Comment by TravisCarden** [comment]
I have confirmed that the problem has to do with the interaction with Workbench Moderation. I can reproduce the problem both in my application and on a fresh installation of Drupal 8.1.x as follows:
1. Install and configure `field_encrypt` and family.
2. Install `workbench_moderation`.
3. Create a new content type.
4. Add an encrypted field.
5. Create a node of the new type, and the encrypted field gets decrypted properly on display and edit.
6. Enable moderation (`workbench_moderation`) on the content type.
7. Create a node of the same type, and the encrypted field does NOT get decrypted properly on display or edit.

Here are the versions of everything I tested with:

``` bash
$ drush core-status drupal-version
 Drupal version   :  8.1.0-beta1

$ drush pm-list --status=enabled --no-core
 Package     Name                                         Type    Version
 Encryption  Field Encrypt (field_encrypt)                Module
 Other       Workbench moderation (workbench_moderation)  Module  8.x-1.0-beta1
 Security    Encrypt (encrypt)                            Module  8.x-3.0-alpha1
 Security    Key (key)                                    Module  8.x-1.1
 Security    Real AES (real_aes)                          Module  8.x-1.0-alpha1
```

(For `field_encrypt` I used the tip of `master` at the time, or `f89f9ff46242a8c56be655f5580e1eb5032bdd20`.)

**Comment by svendecabooter** [comment]
Thanks @TravisCarden for giving details on your setup.
I have been able to reproduce this problem, and created a solution for it.
The code to save the encrypted data was a not optimal and error-prone.
I have now created a better alternative in https://github.com/d8-contrib-modules/field_encrypt/pull/41, which fixes the incompatibilities with workbench_moderation.

**Comment by svendecabooter** [comment]
Hi @TravisCarden,

Can you check with the latest master branch?
You'll have to clear the caches and re-test adding the content, but now it should be compatible with workbench_moderation. Let me know if you're still experiencing issues

**Comment by TravisCarden** [comment]
That fixes it, @svendecabooter! Good work; thanks!
