### ISSUE TITLE
Fatal error: Cannot call abstract method Drupal\Core\Entity\FieldableEntityInterface::baseFieldDefinitions() in field_encrypt/src/Entity/EncryptedFieldValue.php

### ISSUE THREAD

**Issue by TravisCarden** [d8-contrib-modules/field_encrypt#39]
I received the following error on a fresh copy of Drupal 8.0.7 when installing the module and when attempting to visit the site in a browser or interact with it via Drush:

> Fatal error: Cannot call abstract method Drupal\Core\Entity\FieldableEntityInterface::baseFieldDefinitions() in field_encrypt/src/Entity/EncryptedFieldValue.php

**Comment by svendecabooter** [comment]
This calls a method on ContentEntityBase that is available in 8.1.x, but not in 8.0.x.
I'm trying to figure out what the recommended way is to support both branches.

**Comment by svendecabooter** [comment]
Feedback from swentel & bojanz on IRC:
- To solve this properly, we'd have to make 2 branches (field_encrypt-8.0.x and field_encrypt-8.1.x), with appropriate code in each --> i.e. the 8.0.x branch would not call the parent, but implement that logic itself.
- There is a core issue for trying to introduce compatibility checks: https://www.drupal.org/node/2656994
- However: both of them agree not to bother with 8.0.x at this point, since it has only 1 month of life left anyway, before 8.1.x gets released.

**Comment by svendecabooter** [comment]
@nerdstein: do you have an opinion about this, regarding release strategy?
@TravisCarden: is it possible to work with the 8.1.x branch for your project?

**Comment by TravisCarden** [comment]
Thank you, @svendecabooter. We actually _are_ using the 8.1.x branch for our project. I just happened across this bug and reported it as a courtesy. (I probably should've said so.) As far as I'm concerned you can close this issue "won't fix". Thanks!

**Comment by nerdstein** [comment]
I think we should log this incompatibility within the readme for now but eventually fix it. Bear in mind, not everyone in the world is using the bleeding edge. I could see this being a major usability issue due to a lack of a functional 8.0.x version, so I think we need to fix it (eventually).

**Comment by svendecabooter** [comment]
OK.
Once we moved to drupal.org and created a 8.1.x branch / release, we can branch a 8.0.x off of that and provide a fix for 8.0.x, which shouldn't be too hard.

We would then have to keep the 2 versions in mind going forward though, and apply patches to both of them.

**Comment by nerdstein** [comment]
We could create the branches here first, if time permits

**Comment by dawehner** [comment]
At this point in time there is IMHO no reason to support core 8.0.x. It doesn't retrieve security support either.

**Comment by nerdstein** [comment]
Closing
