### ISSUE TITLE
Add a hook that allows you to select whether you want a field/entity to be encrypted as a per  entity basis. (not per entity type)

### ISSUE THREAD

**Issue by arknoll** [d8-contrib-modules/field_encrypt#47]
We would like to be able to have the default for an entity type's fields to be encrypted. But, we would also like to have a hook in place where you can selectively say you would not like any of the fields on the entity to be encrypted.

The use case is this:
1. We are going to be encrypting every field on every content type.
2. We only need the content to be encrypted when a piece of content is unpublished.
3. When a piece of content is published, we would want that revision to be stored unencrypted.

Motivation: For published content, we want to be able to use render cache and not to have the overhead of decrypting content for every field on every piece of content.

**Comment by svendecabooter** [comment]
See the PR referenced above.
I have added your use case to the api.php documentation.
So with a few lines in your custom module, this should work.

**Comment by svendecabooter** [comment]
merged in master!
