### ISSUE TITLE
Incompatibility with Panelizer

### ISSUE THREAD

**Issue by TravisCarden** [d8-contrib-modules/field_encrypt#54]
If I encrypt the `node.panelizer` field `panels_display` property, Panelizer changes cease to save. They seem to, and no errors are shown or logged, but if I refresh the page after the UI indicates it has finished saving, the change I just made will be absent. If I turn off encryption for the property and follow the same steps, it saves and persists just fine.

**Comment by nerdstein** [comment]
Moved the issue to d.o, closing

**Comment by TravisCarden** [comment]
https://www.drupal.org/node/2735925
