### ISSUE TITLE
Workbench moderation + field encrypt + translations isn't working

### ISSUE THREAD

**Issue by arknoll** [d8-contrib-modules/field_encrypt#55]
I just installed these three sets of dependencies and translations aren't being displayed appropriately. Here is what I did.
1. Enabled all modules (workbench moderation, key, encrypt, field encrypt, real_aes, content translations, translate)
2. Set up workflow states (draft, review, publish, archive) and transitions between each state
3. Added workflow to basic page content type
4. Added a test key and encryption profile.
5. Enabled French translation on the site
6. Encrypted the body field on the basic page
7. Created a basic page node and transitioned to review
8. Created a french translation of the node and saved as draft

Expected result, viewing the french draft would display the french content

Actual result, viewing the french draft shows the english content.

This works as expected when workbench moderation is not being used.

**Comment by nerdstein** [comment]
Closing, moved issue to d.o issue queue

**Comment by balsama** [comment]
D.O Issue: https://www.drupal.org/node/2735927
